version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17  # Change to the required Java version
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - mvn clean
  build:
    commands:
      - echo "Building the project..."
      - mvn package
  post_build:
    commands:
      - echo "Build complete!"

artifacts:
  files:
    - target/*.war  # Change to .war if applicable
  discard-paths: yes